import hashlib
import json
from decimal import Decimal, InvalidOperation
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from planner.schemas import Evidence


def _truncate(value: Any, limit: int = 4000) -> Any:
    if value is None:
        return None
    if hasattr(value, "content"):
        value = value.content
    text_value = value if isinstance(value, str) else str(value)
    if len(text_value) <= limit:
        return text_value
    return text_value[:limit] + f"... [truncated {len(text_value) - limit} chars]"


def _canonicalize_number(value: Decimal | float | int) -> int | float:
    """Collapse whole numbers to int so 40, 40.0, and Decimal('40.00') match."""
    if isinstance(value, bool):
        # bool is a subclass of int; keep JSON true/false distinct from 0/1.
        return value
    if isinstance(value, Decimal):
        integral = value.to_integral_value()
        if value == integral:
            return int(integral)
        return float(value)
    if isinstance(value, float):
        return int(value) if value.is_integer() else value
    return int(value)


def _canonicalize_value(value: Any) -> Any:
    """Normalize a cell so hashing matches JSON / DB numeric semantics.

    Planner evidence rows often come from LLM-copied tool output (JSON numbers
    or numeric strings like ``\"40.00\"`` from ``Decimal`` reprs). Verifier
    replay yields SQLAlchemy ``Decimal`` / ``float`` / ``int``. These must hash
    identically when they denote the same number.
    """
    if value is None or isinstance(value, bool):
        return value
    if isinstance(value, str):
        stripped = value.strip()
        if stripped:
            try:
                return _canonicalize_number(Decimal(stripped))
            except InvalidOperation:
                pass
        return value
    if isinstance(value, (Decimal, float, int)):
        return _canonicalize_number(value)
    if isinstance(value, dict):
        return {k: _canonicalize_value(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_canonicalize_value(v) for v in value]
    return value


def fingerprint_rows(evidence: "Evidence | list[list[Any]]") -> str:
    """SHA-256 over a JSON encoding of a queries' result rows.

    :param evidence: Evidence object containing rows (as generated by the planner) or a list of rows (as returned by the database)
    :type evidence: Evidence | list[list[Any]]
    :return: SHA-256 hash of the JSON encoding of the rows
    :rtype: str
    """
    if hasattr(evidence, "rows"):
        evidence = evidence.rows
    payload = json.dumps(
        _canonicalize_value(evidence),
        separators=(",", ":"),
        ensure_ascii=True,
        sort_keys=True,
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()
